apiVersion: 1

datasources:
  - name: KeyPool-OGS MySQL
    type: mysql
    access: proxy
    url: keypool_mysql:3306 
    database: keypool_logs
    user: ogs_user
    secureJsonData:
      password: ogs_password
    jsonData:
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
    isDefault: true
    editable: true